### PR TITLE
Add in_place processing scripts

### PR DESCRIPTION
**Pull request by u9g**
remade `extract_block_lootTables.js` & `patch_states.js` to work on a file not a repo

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
Can you instead add options in existing scripts to avoid duplication ?

**Comment by u9g** [comment]
> Can you instead add options in existing scripts to avoid duplication ?

I think the old one should just be deleted

**Comment by rom1504** [comment]
Then just do it, and use the same name as before instead of the in place folder

**Comment by u9g** [comment]
> Then just do it, and use the same name as before instead of the in place folder

remade the pr here: https://github.com/PrismarineJS/minecraft-jar-extractor/pull/36

**Pull request closed without merging**
